<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="farm_cv" nsURI="http://www.example.org/farm_cv" nsPrefix="farm_cv">
  <eClassifiers xsi:type="ecore:EClass" name="ImageProcessor">
    <eOperations name="fix_aquarium_rotation" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EGenericType"/>
    <eOperations name="fix_background" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EGenericType"/>
    <eOperations name="overlapping_area" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EGenericType"/>
    <eOperations name="redraw_layout" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EGenericType"/>
    <eOperations name="exec_analysis" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EGenericType"/>
    <eOperations name="getInstance" eType="#//ImageProcessor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericAquarium">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="center_coord_X" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="center_coord_Y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CameraObject" eSuperTypes="#//GenericAquarium">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rotation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnalyzedAnimal" eSuperTypes="#//Fish">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="X_pos" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Y_pos" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fish">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shape" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cv_Controller">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="processor" eType="#//ImageProcessor.1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="build" eType="#//OutputBuilder.1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ImageProcessor" instanceClassName="ImageProcessor"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutputBuilder">
    <eOperations name="apply_heatmap" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EGenericType"/>
    <eOperations name="assemble_frames" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EGenericType"/>
    <eOperations name="output_video" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EGenericType"/>
    <eOperations name="getInstance" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EGenericType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="OutputBuilder" instanceClassName="OutputBuilder"/>
</ecore:EPackage>
